name: Hello World
author: William Cabiam
description: Some Description
inputs:
  who-to-greet:
    description: 'Who to greet'
    required: true
    default: William
outputs:
  time:
    description: 'The greeting time'
runs:
  using: 'node12'
  main: 'dist/index.js'