
on: push
jobs:
  testing-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Execute hello action
        uses: ./.github/actions/hello
        with:
          who-to-greet: "World"
      - run: |
          echo "Time: ${{ steps.hello.outputs.time }}"
      - uses: ./.github/actions/issue
        id: issue
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: title
          body: body
          assignees: |
            'cabiamdos'
      - run: |
          echo ${{ steps.issue.outputs.issue }}
      - name: Execute hello action docker
        if: always()
        uses: ./.github/actions/hello-docker
        with:
          who-to-greet: "World"
      - name: Send a slack message
        if: always()
        uses: ./.github/actions/slack-php
        with:
          slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
          message: Hello slack