
name: CI
on:
  pull_request:
    branches: [develop]
  push:
    branches: [develop]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache node_modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: node-${{ hashFiles('**/package-lock.json') }}
      - name: Use NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"
      - run: |
          cd react-app
          npm i
          npm ci
      - run: |
          cd react-app
          npm run format:check
      - run: |
          cd react-app
          npm run test -- --coverage
        env:
          CI: true
      - name: Build Project
        if: github.event_name == 'push'
        run: |
          cd react-app
          npm run build
      - name: Deploy to Staging
        if: github.event_name == 'push'
        run: |
          cd react-app
          npx surge --project ./build --domain elegant-ice.surge.sh
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}